(function( $ ) {
	'use strict';

    /**
     * arterosil_ajaxurl = holds ajax url
     */
    var GLOBALS = {
        ajaxurl:arterosil_ajaxurl,
    };

    var ORDERFORM = {
            cart: {},
            productList: null
        }, APPDATA = {
            products: JSON.parse(escapeSpecialChars( productsString ))
        };

    $(document).ready(function(){
        initData();
        initProductSelect2();
        initQuantityChangeHandler();
        initAddProductButton();
        console.log('APPDATA >> ', APPDATA);
    });

    /**
     * Load Dependencies and Data
     */
    function initData(){
        //load user data
        if(USERID){
            var args = {
                userID:USERID,
                action:'getUser',
                nonce:''
            };
            $.post(arterosil_ajaxurl,args)
            .done(function(data){
                APPDATA['user'] = data;
            })
            .fail(function(data){
                console.error("Error while fetching User Data");
            });
        }
    }

    /**
     * Initializes Add Product Button generated by the "Order Form" endpoint.
     */
    function initAddProductButton(){
        $('[data-aaction="addProduct"]').on('click',function(e){
            e.preventDefault();
            $(this).hide();
            $(this).closest('.product-list').find('.add-product-wrapper').removeClass('a-hidden');
            
            //alert( $(this).closest('.add-product-wrapper'));

        });

        //attach event to add to cart button
        $('.btn[data-aaction="addToCart"]').on('click',function(e){
            e.preventDefault();
            $(this).closest('.add-product-wrapper')
            .addClass('a-hidden')
            .prev().show();

            //inject product items
            if(ORDERFORM.productList[0].$$selected){
                ORDERFORM.cart[ORDERFORM.productList[0].$$selected.value] = {
                    text:       ORDERFORM.productList[0].$$selected.text,
                    quantity:  ORDERFORM.productList[0].$$selected.quantity
                };
                renderCartView();
            }

        });
    }

    /**
     * Rend Cart View
     */
    function renderCartView(){

        if(!$.isEmptyObject(ORDERFORM.cart)){
            
            var ret = "<tr> <th>ID</th> <th>Item</th> <th>Qty</th> <th></th> </tr>";
            for(var key in ORDERFORM.cart){
                ret += '<tr id="'+key+'"> <td>'+key+'</td>  <td>'+ORDERFORM.cart[key].text+'</td>  <td>'+ORDERFORM.cart[key].quantity+'</td> <td><a href="#" class="remove">REMOVE</a></td>:</tr>';
            }

            // REMOVE button is clicked on the cart
            var table = $(ret);
            //console.log( table.find('.remove').length);
            table.find('.remove').on('click',function(e){
                e.preventDefault();
                var id = $(this).closest('tr').attr('id');
                delete ORDERFORM.cart[id];
                renderCartView();
            });

            $('.product-list').removeClass('no-items')
            .find('table.product-list-table').html("").append(table);
            
        }
        else {
            $('.product-list').addClass('no-items')
            .find('table.product-list-table').html("");    
        }
        
    }

    /**
     * Init Product Select 2 Dropdown
     */
    function initProductSelect2(){
        //initialize select2 for products
        ORDERFORM
        .productList = $('.wc-product-list')
        .select2({ placeholder: 'Select Product'})                //init
        .on('change', function(e){  //bind change event
            e.currentTarget['$$selected'] = {
                quantity: $(e.currentTarget).closest('.add-product-wrapper').find('input[name="product-quantity"]').val(),
                text: e.currentTarget.options[e.currentTarget.options.selectedIndex].text,
                value: e.currentTarget.options[e.currentTarget.options.selectedIndex].getAttribute('value')
            };
        });
    }

    /**
     * Init On Change Handler For Quantity field
     */
    function initQuantityChangeHandler(){
        //Bind change event for Quantity field
        ORDERFORM
        .productList
        .closest('.add-product-wrapper').find('input[name="product-quantity"]')
        .on('change', function(e){
            if(typeof ORDERFORM.productList[0]['$$selected'] === 'undefined'){
                ORDERFORM.productList[0]['$$selected'] = {};  
            }
            ORDERFORM.productList[0].$$selected['quantity'] = e.currentTarget.value;
        });
    }


    /**
     * UTILITY FUNCTIONS
     */
    function escapeSpecialChars(jsonString) {

        return jsonString.replace(/\n/g, "\\n")
            .replace(/\r/g, "\\r")
            .replace(/\t/g, "\\t")
            .replace(/\f/g, "\\f");

    }
    
})( jQuery );
